### ISSUE TITLE
Strange look of Monterey

### ISSUE THREAD

**Issue by PrzemekSkw** [vinceliuice/Monterey-kde#2]
Hello, I install Monterey theme. Set Global Theme in KDE settings and then set Monterey in Kvantum Manager. My Plasma theme and Dolphin don't look like in the screenshots.

![Screenshot_20210924_163149](https://user-images.githubusercontent.com/25219988/134693886-ea0cf1ae-248e-4fc3-8f5e-65f136d6da22.png)
![Screenshot_20210924_164037](https://user-images.githubusercontent.com/25219988/134693892-c26c032f-fde3-453f-bb35-c8350f183e39.png)

Regards,
Przemek

**Comment by YuvanMichael** [comment]
If you wanna use a macos monterey theme. Get kde set up correctly! Kvantum etc are required! Manjaro kde works best with this theme. It also works better with Cupertino Icons (Cupertino monterey) Here's my setup. (Manjaro Linux). 
![Screenshot_20220225_104055](https://user-images.githubusercontent.com/86945563/155657643-c0cc9ff3-4df6-4dc2-833e-29ddfe56e54e.png)

**Comment by YuvanMichael** [comment]
There are youtube videos on how to get this set up.

**Comment by YuvanMichael** [comment]
Requires a little bit of configuration. 30 min. Mininimum. But once you get it set up, it looks so good. It's almost like you have actual macos running on your system.

**Comment by YuvanMichael** [comment]
Latte dock is required too.

**Comment by YuvanMichael** [comment]
Don't use latte layout files. They don't work well. With All corners and screen edge or something. You can get latte dock to be like this.

**Comment by PrzemekSkw** [comment]
Thanks, but I'm not using KDE anymore. Too buggy for me.
Regards.
